### ISSUE TITLE
Updated from 2.1.2 to 2.2.0, all my stone fences are gone...

### ISSUE THREAD

**Issue by calloatti** [Shnupbups/extra-pieces#16] opened 2019-07-22 23:33 UTC
![2019-07-22_20 28 54](https://user-images.githubusercontent.com/12817862/61671810-90d32b00-acbf-11e9-97c7-36996cf4410f.png)

I never touched the default config in both versions. How do I bring stonce fences back?

**Comment by calloatti** [comment] 2019-07-22 23:37
I think my mistake was deleting the old config\extrapieces.json

I thought that would be regenerated on config\extrapieces\piecepacks\default.json

So, do we have to keep config\extrapieces.json around then?

**Comment by Shnupbups** [comment] 2019-07-22 23:57
This shouldn't be happening! Can you send me a copy of your default.json piecepack?

**Comment by calloatti** [comment] 2019-07-23 00:05
Here you go: https://paste.ee/p/vGt2m

This is exactly what I did:

1. Updated to 2.2.0
2. Loaded world
3. Exit world, close Minecraft
4. Deleted config\extrapieces.json
5. Deleted the folder config\extrapieces
(I tought the default config of the new version would be regenerated)
6. Start Minecraft, load world, found stone fences vanished. Also, no stone fences in REI
7. Exit world, close Minecraft
8. Restore config\extrapieces.json from recycle bin. 
9. Start Minecraft, load world, of course my stone fences are still gone, but they are back in REI

EDIT: It's not a big deal for me, but it seems there is way to totally bork everything just by doing stuff like what I describe

**Comment by Shnupbups** [comment] 2019-07-23 05:46
`config/extrapieces.json` isn't used at all anymore, deleting that was the cause of the problem and restoring it wasn't the solution.
I believe what's happened here is that, when launching Minecraft with the new version, it created `default.json` but didn't load it for some reason, causing no pieces to be registered.
Then on the second load, `default.json` already existed from the first time and so it _did_ load it.
I think that there may be a problem with loading the config on the same game run as it is created.

**Comment by calloatti** [comment] 2019-07-23 06:25
OK confirmed the issue is when running Minecraft for the first time with the mod and there is no config.

1. deleted .minecraft\config\extrapieces
2. Start MC, load a saved world, search stone fence in REI, nothing
3. Exit world, close Minecraft
4. Restart Minecraft, enter same world, search stone fence in REI, found!

**Comment by Shnupbups** [comment] 2019-07-23 07:18
This will be fixed in 2.2.1! Apologies for the loss of your stone fences and any other issues this may have caused.

**Closed as completed** 2019-07-23 07:29 UTC
Labels: bug
