### ISSUE TITLE
Vanilla fences not connecting

### ISSUE THREAD

**Issue by ItsCestial** [Shnupbups/extra-pieces#2] opened 2019-04-24 02:00 UTC
None of the vanilla fences can connect to each other. All of the added fences connect just fine. If you try to connect a vanilla fence to a fence added by this mod, it works some of the time.

I'm using the full 1.14 release with a snapshot version of your mod so that might be the cause of the issue, but just in case it's not, I'm letting you know.

![javaw_0Iyir5y44H](https://user-images.githubusercontent.com/38892324/56627264-df5a2600-65f9-11e9-8d3b-49e099678775.png)

**Comment by Shnupbups** [comment] 2019-04-24 07:10
And you're using the latest version of Extra Pieces? Odd.
The issue shown in your image should only occur if the vanilla fences didn't have the 'fence' block tag.
Note that Fences only connect to other fences of the same Material type, i.e. fences made of wood only connect to fences also made of (any other type of) wood.
But the Cobblestone fence and the Nether Brick fence should connect, (as their materials are both 'stone') as shown by the Nether Brick one trying but the Cobblestone not reciprocating.
Could you please take a screenshot of you looking at the Nether Brick fence with F3 on? Cheers.

**Comment by ItsCestial** [comment] 2019-04-24 09:35
Yeah I'm using 1.2.0 (uploaded Apr. 10). Vanilla fences aren't even connecting to each other at all. Entities still think that they are connected and try to path around them but neither the hitbox or visual are there.
![javaw_Y0rEtelYm4](https://user-images.githubusercontent.com/38892324/56649190-87dbaa80-6639-11e9-9eb5-87273793ea7d.png)

**Comment by Shnupbups** [comment] 2019-04-24 11:40
That's really odd, especially as its not happening on my end. Are you running any other mods? If so, could I have a list?

**Comment by ItsCestial** [comment] 2019-04-24 18:59
My mods list is:

Extra Pieces
I Am Very Smart - https://minecraft.curseforge.com/projects/i-am-very-smart
More Layers - https://minecraft.curseforge.com/projects/more-layers
Silky Spawners - https://minecraft.curseforge.com/projects/silky-spawners

I have already tried removing all of the other ones but the issue was still there.

**Comment by VegethB** [comment] 2019-05-02 07:46
Same thing for me too.
Fabric 1.14 b7; Loader 0.4.6; Binary141.
Mod List:
  Adorn-0.1.3 1.14
  amethystmod-1.0.1
  appleskin-mc1.14-fabric-1.0.5
  ArcaneMagic-1.0-beta2
  ash-1.1.2
  auto-config-1.0.1 mc1.14
  cotton-0.6.1 1.14-SNAPSHOT
  crawl-0.5.4
  durabilityviewer-1.14-fabric0.2.7-1.5
  easierchests-1.14-fabric0.2.7-1.3.1
  extrapieces-1.2.0
  fabric-0.2.7 build.127
  fabric-language-kotlin-1.3.30+build.2
  foamfix-0.12.1
  Hwyla-fabric-1.14-1.9.16-60
  LightOverlay-1.1.0.6
  ModMenu-1.5.2-82
  REIAddons-1.1.0
  RoughlyEnoughItems-2.8.0.100
  shulkerboxtooltip-1.2.0 1.14.0
  SimpleZoom-1.0.0.14-universal
  stockpile-1.0.2 1.14
  the-biome-overhaul-1.1.1
  vanilla-hammers-1.1.3
  vanilla-toolsets-1.1.1

**Comment by deli73** [comment] 2019-05-17 06:03
this also affects vanilla walls!

just checked and this happens with nothing but the fabric api and the mod

**Comment by LemmaEOF** [comment] 2019-05-17 06:08
This might be because the [tags](https://github.com/Shnupbups/extra-pieces/tree/master/src/main/resources/data/minecraft/tags/blocks) don't set `"replace": false` explicitly. That might be tripping Minecraft up. If you put those in, it may fix the issue in production!

**Comment by deli73** [comment] 2019-05-17 06:17
for the time being i made a datapack that fixes it, hopefully

**Comment by Shnupbups** [comment] 2019-05-17 06:37
@Boundarybreaker I only *just* pushed the commit that removes that line, in an attempt to perhaps *fix* this issue. In all released versions of the mod, the line *is* present.
I removed it as the Minecraft Wiki states that `replace` defaults to `false`, so theoretically I shouldn't need it. I have no idea if removing the line fixes the issue (nor do I have any idea why it would, but then I also have no idea why the issue is happening in the first place) but its absence is most definitely not the cause.
This issue only seems to affect some users, and once again I have no clue as to why.

**Comment by Shnupbups** [comment] 2019-05-17 10:20
Should be fixed in 1.3.0. Not ideal the way I had to do it, but eh. Better than it being broken.

**Closed as completed by Shnupbups** 2019-05-17 10:20 UTC
Labels: bug
