### ISSUE TITLE
Crash when opening world with Tweed installed

### ISSUE THREAD

**Issue by Rahmiel** [Shnupbups/extra-pieces#11] opened 2019-07-13 10:50 UTC
I've tested every mod one by one in this pack, and since updating Extra Pieces is the only mod I can't get working. My world heavily relies on Extra Pieces, and the new features just have me in a very good mood, so I kinda can't live without you!

So without extra pieces things are fine. Once the mod is enabled (installed) I am able to get to the main menu, but upon loading a world (clean, creative, flat world) the client freezes up on world generation at 100% and will not move. Log claims that the player is being disconnected due to some stuff I don't understand.

Working Log (No Extra Pieces): https://paste.ee/p/9JDJf

Crashing Log (Extra Pieces Installed): https://paste.ee/p/X7Shi

Edit1: This issue only exists with 2.x.x versions of Extra Pieces. 1.3.0 Still works perfectly fine.

**Comment by Shnupbups** [comment] 2019-07-13 13:15
The issue appears to be with Tweed. Not sure why it doesn't occur when Extra Pieces is not present, but I would suggest removing Tweed unless you have a mod that requires it, as it is known to have issues.

**Comment by Rahmiel** [comment] 2019-07-13 21:52
So something must have tweed imbedded because I can't for the life of me find the mod in my jarfiles. I'm going to have to continue digging, or just use Extra Pieces 1.3.0 for now.

**Comment by Rahmiel** [comment] 2019-07-13 22:03
So I can confirm the issue is with Tweed, as after disabling the mod MouseWheelie, made by the same author, Extra Pieces loads. However, I wouldn't mark it up to that completely, just a suggestion, as a mod author you guys need to communicate seeings as the issue seems to be dealing with both mods. You might not think so on the cover, but something isn't playing nice underneath, and it will probably take both of you to find the issue, and improve upon something for everyone. Don't let the Fabric community turn into Forge, where every modder seems to be only in it for themselves. I'm not saying anything, I'm just suggesting that a little cooperation could solve this issue, and possibly help the Fabric community overall.

**Comment by Shnupbups** [comment] 2019-07-14 00:21
The only reason Extra Pieces and Tweed might conflict is because of Extra Pieces' embedded dependency, namely, Artifice. Artifice is developed by SwordGlowsBlue, not myself.

I'm sorry, but I really can't do anything in this situation other than alert the authors of Tweed and Artifice that there may be a compatibility issue.

**Comment by kgscialdone** [comment] 2019-07-14 00:35
Looks like a refmap error on Tweed's end, judging by the crash log. Not much I can do about it on Artifice's end, it doesn't appear to be an issue with mixin compatibility - I couldn't tell you why it only crashes together.

**Comment by Shnupbups** [comment] 2019-07-14 00:47
The only other thing embedded in Extra Pieces is Jankson, which I suppose could potentially be the cause of the conflict? I don't really see why, but maybe.

That or it somehow is Extra Pieces itself that conflicts. Completely lost if that's the case.

**Comment by Shnupbups** [comment] 2019-07-14 00:50
Okay, Jankson doesn't have any mixins so it's not that. But Extra Pieces also doesn't have any mixins, so... I'm completely lost. It must be entirely on Tweed's end. No idea why it only happens alongside Extra Pieces.

**Comment by Rahmiel** [comment] 2019-07-20 07:59
Well, I will leave this up for now if you want to reference it. If you want to close it you can. Siphalor doesn't seem interested in paying attention to Tweed or any of his mods for Fabric for that matter. Sometimes I wonder if I should start modding, not that you guys don't do a great job, and I really do appreciate you guys looking into this. For now, Extra Pieces > MouseWheelie, so I'm not worried about it.

**Comment by kgscialdone** [comment] 2019-07-20 20:52
The heart of this issue seems to be this: 
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on handler$onGameJoined$zbf000 could not find any targets matching 'onGameJoin' in the target class net.minecraft.class_634. Using refmap build-refmap.json
```

[Here's the relevant code](https://github.com/Siphalor/tweed-api/blob/2.2.0-beta.5/src/main/java/de/siphalor/tweed/client/mixin/MixinClientPlayNetworkHandler.java).

Essentially, this breaks down to one of a few problems:

1. The method being targeted doesn't exist anymore (possible).
2. The method being targeted has changed intermediary names and the refmap is out of date (unlikely).
3. The refmap was built incorrectly and doesn't have the information it needs (possible?).
4. The mixin never worked in the first place (very unlikely).
5. Something I'm not thinking of (entirely possible).

There really isn't anything anyone but @Siphalor can do to fix this, unless someone wants to work out a fix and PR it to Tweed; even then, it would require Siph to actually merge that PR, which seems unlikely to happen anytime soon (he's been marked as "afk - use Telegram" on the Fabric Discord server since the end of last month, and is marked as "afk for quite some time" in his Github status as well).

I'm still baffled as to why this issue only crops up when both Artifice and Tweed are present, but that's mixins for you. Shit gets weird sometimes.

**Closed as completed** 2019-07-22 07:33 UTC

**Comment by Siphalor** [comment] 2019-07-22 08:07
I'm back now from vacation but actually this issue results as the used version of MW / Tweed seems to be out-dated please update and try again.
